-- -------------------------- SELECT --------------------------------------
--SELECT USER_ID, USERNAME, PASSWORD, EMAIL, TYPE, TYPE_ID FROM USER;
--SELECT ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR FROM DONOR;
--SELECT ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR FROM PATIENT;
--SELECT PAIR_ID, PATIENT_ID, BLOOD_TYPE_PATIENT, DONOR_ID, BLOOD_TYPE_DONOR, THEY_ARE_COMPATIBLE FROM PAIR_PATIENT_DONOR;
--SELECT FIRST_PATIENT_ID, FIRST_DONOR_ID,	SECOND_PATIENT_ID, SECOND_DONOR_ID, IS_ONLY_TWO_CYCLE, THIRD_PATIENT_ID, THIRD_DONOR_ID , IS_THREE_CYCLE FROM VALIDATED_CYCLE;

---------------------------------   INSERT -------------------------------------------------------------------------------

INSERT INTO USER(USERNAME, EMAIL, PASSWORD, TYPE, TYPE_ID) VALUES('admin', 'admin@mail.com', 'password', 'admin', 0);
INSERT INTO USER(USERNAME, EMAIL, PASSWORD, TYPE, TYPE_ID) VALUES('ionut.dima', 'ionut.dima@gmail.com', '210497', 'donor', 1);
INSERT INTO USER(USERNAME, EMAIL, PASSWORD, TYPE, TYPE_ID) VALUES('Alex', 'alex@gmail.com', '123456', 'patient', 1);
--
----
INSERT INTO PATIENT(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES (1, 'Alex', 'Popescu', 'AB', 'HLA', TO_DATE('17/12/2019', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Bogdan', 'Pipata', '0', 'HLA', TO_DATE('17/11/2019', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Marius', 'Piscu', 'B', 'HLA', TO_DATE('17/09/2019', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('George', 'Apopei', 'A', 'HLA', TO_DATE('17/08/2019', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Marian', 'Tudose', 'AB', 'HLA', TO_DATE('07/06/2020', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('George', 'Tudoran', 'A', 'HLA', TO_DATE('08/06/2020', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Mircea', 'Bravo', 'A', 'HLA', TO_DATE('09/06/2020', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Cosmin', 'Miclea', '0', 'HLA', TO_DATE('10/06/2020', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Daniel', 'Urse', 'B', 'HLA', TO_DATE('11/06/2020', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Andrei', 'Branza', '0', 'HLA', TO_DATE('12/06/2020', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Mihail', 'Stoica', 'AB', 'HLA', TO_DATE('13/06/2020', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Aurelian', 'Alexandrescu', 'B', 'HLA', TO_DATE('14/06/2020', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Florin', 'Marginean', '0', 'HLA', TO_DATE('15/06/2020', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Tinis', 'Acristei', 'AB', 'HLA', TO_DATE('16/06/2020', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Darius', 'Dudau', 'B', 'HLA', TO_DATE('17/06/2020', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Elena', 'Comarzan', '0', 'HLA', TO_DATE('18/06/2020', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Raluca', 'Ignatencu', 'A', 'HLA', TO_DATE('19/06/2020', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Mihaela', 'Bahnariu', 'AB', 'HLA', TO_DATE('20/06/2020', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Theodor', 'Neculai', 'B', 'HLA', TO_DATE('21/06/2020', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Iuliana', 'Antonov', '0', 'HLA', TO_DATE('22/06/2020', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Antonia', 'Albu', '0', 'HLA', TO_DATE('22/06/2020', 'DD/MM/YYYY'), false);
INSERT INTO PATIENT(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(34, 'Francisca', 'Cochior', 'A', 'cochior.francisca', 'Bacau', TO_DATE('2020-06-16', 'YYYY-MM-DD'), TRUE);
INSERT INTO PATIENT(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(35, 'Nicoleta', 'Albu', '0', 'albu.nicoleta', 'Bacau', TO_DATE('2020-06-16', 'YYYY-MM-DD'), TRUE);
INSERT INTO PATIENT(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(36, 'Elena', 'Gaman', 'A', 'gaman.elena', 'Bacau', TO_DATE('2020-06-16', 'YYYY-MM-DD'), TRUE);
INSERT INTO PATIENT(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(37, 'Antonia', 'Puscasu', 'A', 'puscasu.antonia', 'Iasi', TO_DATE('2020-06-16', 'YYYY-MM-DD'), TRUE);
INSERT INTO PATIENT(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(38, 'Iulia', 'Putanu', '0', 'putanu.iulia@gmail.com', 'Iasi', TO_DATE('2020-06-16', 'YYYY-MM-DD'), TRUE);
INSERT INTO PATIENT(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(39, 'Petronela', 'Antonie', '0', 'antonia.petronela', 'Iasi', TO_DATE('2020-06-16', 'YYYY-MM-DD'), TRUE);
INSERT INTO PATIENT(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(40, 'Maria', 'Tulpan', 'A', 'tulpan.maria@gmail.com', 'Iasi', TO_DATE('2020-06-16', 'YYYY-MM-DD'), TRUE);
INSERT INTO PATIENT(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(41, 'Raluca', 'Vladila', 'B', 'vladila.raluca@gmail.com', 'Buzau', TO_DATE('2020-06-16', 'YYYY-MM-DD'), TRUE);
INSERT INTO PATIENT(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(42, 'Mihai', 'Matei', '0', 'matei.mihai@gmail.com', 'Bacau', TO_DATE('2020-06-16', 'YYYY-MM-DD'), TRUE);
INSERT INTO PATIENT(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(43, 'Stefan', 'Dumbrava', 'B', 'dumbrava.stefan', 'Bacau', TO_DATE('2020-06-16', 'YYYY-MM-DD'), TRUE);

INSERT INTO DONOR(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES (1, 'Ionut', 'Popescu', 'B', 'HLA', TO_DATE('17/07/2019', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Tiberiu', 'Pipota', 'A', 'HLA', TO_DATE('17/05/2019', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Cristian', 'Paunescu', '0', 'HLA', TO_DATE('17/06/2019', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Calin', 'Praslea', 'AB', 'HLA', TO_DATE('17/08/2019', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Catalina', 'Prinsu', '0', 'HLA', TO_DATE('16/05/2020', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Nicoleta', 'Strojoiu', 'A', 'HLA', TO_DATE('17/05/2020', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Madalin', 'Spanache', 'B', 'HLA', TO_DATE('18/05/2020', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Anamaria', 'Suciu', '0', 'HLA', TO_DATE('19/05/2020', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Valentina', 'Mitu', 'AB', 'HLA', TO_DATE('20/05/2020', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Andreea', 'Oruna', 'A', 'HLA', TO_DATE('21/05/2020', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Lucian', 'Palade', '0', 'HLA', TO_DATE('22/05/2020', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Alexandra', 'Dutu', 'AB', 'HLA', TO_DATE('23/05/2020', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Laura', 'Mischie', '0', 'HLA', TO_DATE('24/05/2020', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Marinela', 'Ignat', 'B', 'HLA', TO_DATE('25/05/2020', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Andreea', 'Tutuianu', '0', 'HLA', TO_DATE('26/05/2020', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Dorina', 'Ciulavu', 'A', 'HLA', TO_DATE('27/05/2020', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Adelina', 'Ivanov', '0', 'HLA', TO_DATE('28/05/2020', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Madalina', 'Neacsu', '0', 'HLA', TO_DATE('29/05/2020', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(FIRST_NAME, LAST_NAME, BLOOD_TYPE, GENE, ARRIVING_TIME, HAS_PAIR) VALUES ('Matei', 'Mihalcea', 'AB', 'HLA', TO_DATE('30/05/2020', 'DD/MM/YYYY'), false);
INSERT INTO DONOR(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(68, 'Cristina' ,'Ciuca', 'B', 'ciuca.cristina', 'Bacau', TO_DATE('2020-06-16', 'YYYY-MM-DD'), TRUE);
INSERT INTO DONOR(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(69, 'Dragos', 'Luca' ,'AB', 'luca.dragos', 'Bacau', TO_DATE('2020-06-17', 'YYYY-MM-DD'), TRUE);
INSERT INTO DONOR(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(70, 'Cristina', 'Calin', 'AB', 'calin.cristina@gmail.com', 'Bacau', TO_DATE('2020-06-18', 'YYYY-MM-DD'), TRUE);
INSERT INTO DONOR(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(71, 'Rares', 'Serban', 'A', 'serban.rares', 'Bacau', TO_DATE('2020-06-19', 'YYYY-MM-DD'), TRUE);
INSERT INTO DONOR(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(72, 'Adriana', 'Toncu', 'A', 'toncu.adriana@gmail.com', 'Iasi', TO_DATE('2020-06-20', 'YYYY-MM-DD'), TRUE);
INSERT INTO DONOR(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(73, 'Bianca', 'Drimba', '0', 'drimba.bianca', 'Iasi',	TO_DATE('2020-06-21', 'YYYY-MM-DD'), TRUE);
INSERT INTO DONOR(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(74, 'Ana', 'Tilita', 'AB', 'tilita.ana@gmail.com', 'Bacau', TO_DATE('2020-06-22', 'YYYY-MM-DD'), TRUE);
INSERT INTO DONOR(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(75, 'Alina', 'Filip', 'B', 'filip.alina', 'Bacau', TO_DATE('2020-06-23', 'YYYY-MM-DD'), TRUE);
INSERT INTO DONOR(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(76, 'Anda', 'Lazar', 'A',	'lazar.anda@gmail.com', 'Buzau', TO_DATE('2020-06-24', 'YYYY-MM-DD'), TRUE);
INSERT INTO DONOR(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(77, 'Gabriela', 'Iacob', 'A',	'iacob.gabriela', 'Iasi', TO_DATE('2020-06-25', 'YYYY-MM-DD'), TRUE);
INSERT INTO DONOR(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(78, 'Daniela', 'Danciu', 'AB',	'daniela.danciu@gmail.com', 'Brasov', TO_DATE('2020-06-26', 'YYYY-MM-DD'), FALSE);
INSERT INTO DONOR(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(79, 'Vlad', 'Tecusan', '0',	'vlad.tecusan@gmail.com', 'Brasov', TO_DATE('2020-06-27', 'YYYY-MM-DD'), FALSE);
INSERT INTO DONOR(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(80, 'Ramona', 'Motca', 'B',	'ramona.motca@gmail.com', 'Brasov', TO_DATE('2020-06-28', 'YYYY-MM-DD'), FALSE);
INSERT INTO DONOR(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(81, 'Ionela', 'Gandac', '0',	'ionela.gandac@gmail.com', 'Brasov', TO_DATE('2020-06-29', 'YYYY-MM-DD'), FALSE);
INSERT INTO DONOR(ID, FIRST_NAME, LAST_NAME, BLOOD_TYPE, EMAIL, CITY, ARRIVING_TIME, HAS_PAIR) VALUES(82, 'Teodora', 'Negru', 'A',	'teodora.negru@gmail.com', 'Brasov', TO_DATE('2020-06-30', 'YYYY-MM-DD'), FALSE);


INSERT INTO PAIR_PATIENT_DONOR(PATIENT_ID, BLOOD_TYPE_PATIENT, DONOR_ID, BLOOD_TYPE_DONOR, THEY_ARE_COMPATIBLE ) VALUES(34, 'A', 68, 'B',	FALSE);
INSERT INTO PAIR_PATIENT_DONOR(PATIENT_ID, BLOOD_TYPE_PATIENT, DONOR_ID, BLOOD_TYPE_DONOR, THEY_ARE_COMPATIBLE ) VALUES(35, 'B', 69, 'AB', FALSE);
INSERT INTO PAIR_PATIENT_DONOR(PATIENT_ID, BLOOD_TYPE_PATIENT, DONOR_ID, BLOOD_TYPE_DONOR, THEY_ARE_COMPATIBLE ) VALUES(36, '0', 70,'AB', FALSE);
INSERT INTO PAIR_PATIENT_DONOR(PATIENT_ID, BLOOD_TYPE_PATIENT, DONOR_ID, BLOOD_TYPE_DONOR, THEY_ARE_COMPATIBLE ) VALUES(37, 'A', 71, 'A', TRUE);
INSERT INTO PAIR_PATIENT_DONOR(PATIENT_ID, BLOOD_TYPE_PATIENT, DONOR_ID, BLOOD_TYPE_DONOR, THEY_ARE_COMPATIBLE ) VALUES(38, 'A', 72, 'A',	TRUE);
INSERT INTO PAIR_PATIENT_DONOR(PATIENT_ID, BLOOD_TYPE_PATIENT, DONOR_ID, BLOOD_TYPE_DONOR, THEY_ARE_COMPATIBLE ) VALUES(39, '0', 73, '0', TRUE);
INSERT INTO PAIR_PATIENT_DONOR(PATIENT_ID, BLOOD_TYPE_PATIENT, DONOR_ID, BLOOD_TYPE_DONOR, THEY_ARE_COMPATIBLE ) VALUES(40, '0', 74, 'AB', FALSE);
INSERT INTO PAIR_PATIENT_DONOR(PATIENT_ID, BLOOD_TYPE_PATIENT, DONOR_ID, BLOOD_TYPE_DONOR, THEY_ARE_COMPATIBLE ) VALUES(41, 'A', 75, 'B',	FALSE);
INSERT INTO PAIR_PATIENT_DONOR(PATIENT_ID, BLOOD_TYPE_PATIENT, DONOR_ID, BLOOD_TYPE_DONOR, THEY_ARE_COMPATIBLE ) VALUES(42, '0', 76, 'A', FALSE);
INSERT INTO PAIR_PATIENT_DONOR(PATIENT_ID, BLOOD_TYPE_PATIENT, DONOR_ID, BLOOD_TYPE_DONOR, THEY_ARE_COMPATIBLE ) VALUES(43, 'B', 77,	'A', FALSE);

--INSERT INTO VALIDATED_CYCLE(FIRST_PATIENT_ID, FIRST_DONOR_ID,	SECOND_PATIENT_ID, SECOND_DONOR_ID, IS_ONLY_TWO_CYCLE, THIRD_PATIENT_ID, THIRD_DONOR_ID , IS_THREE_CYCLE) VALUES(1, 4, 3, 4, TRUE, null, null, false);

--INSERT INTO VALIDATED_CYCLE(FIRST_PATIENT_ID, FIRST_DONOR_ID,	SECOND_PATIENT_ID, SECOND_DONOR_ID, IS_ONLY_TWO_CYCLE, THIRD_PATIENT_ID, THIRD_DONOR_ID , IS_THREE_CYCLE) VALUES(1, 4, 3, 4, FALSE, 2, 3, TRUE);